(function attachFallbackPerpUniverse(root, factory) {
  const payload = factory();
  if (typeof module === "object" && module.exports) {
    module.exports = payload;
  }
  root.APEX_FALLBACK_PERPS = payload;
})(typeof globalThis !== "undefined" ? globalThis : this, function buildFallbackPerpUniverse() {
  const QUOTE_ASSET = "USDT";
  const DEFAULT_QUANTITY_PRECISION = 3;
  const FALLBACK_BASE_ASSETS = [
    ["BTC", 2],
    ["ETH", 2],
    ["BNB", 2],
    ["SOL", 2],
    ["XRP", 4],
    ["ADA", 4],
    ["DOGE", 5],
    ["LINK", 3],
    ["AVAX", 3],
    ["LTC", 2],
    ["BCH", 2],
    ["DOT", 3],
    ["TRX", 5],
    ["TON", 3],
    ["SUI", 4],
    ["APT", 3],
    ["NEAR", 3],
    ["SEI", 4],
    ["ARB", 4],
    ["OP", 4],
    ["INJ", 3],
    ["ATOM", 3],
    ["TIA", 3],
    ["TAO", 2],
    ["RENDER", 3],
    ["FET", 4],
    ["ENA", 4],
    ["WLD", 3],
    ["JUP", 4],
    ["PENDLE", 3],
    ["ONDO", 4],
    ["POL", 4],
    ["FIL", 3],
    ["ETC", 2],
    ["XLM", 5],
    ["AAVE", 2],
    ["MKR", 2],
    ["LDO", 4],
    ["UNI", 3],
    ["ICP", 2],
    ["IMX", 4],
    ["AXS", 3],
    ["SAND", 4],
    ["MANA", 4],
    ["GALA", 5],
    ["CHZ", 5],
    ["EOS", 4],
    ["COMP", 2],
    ["SNX", 4],
    ["CRV", 4],
    ["DYDX", 3],
    ["ZEC", 2],
    ["DASH", 2],
    ["NEO", 2],
    ["KAVA", 4],
    ["RUNE", 3],
    ["YFI", 2],
    ["EGLD", 2],
    ["SUSHI", 4],
    ["ALGO", 5],
    ["KSM", 2],
    ["ZIL", 5],
    ["ICX", 4],
    ["STX", 4],
    ["KAS", 5],
    ["NOT", 6],
    ["BLUR", 4],
    ["ACE", 4],
    ["ALT", 5],
    ["NTRN", 4],
    ["MEME", 5],
    ["BOME", 6],
    ["POPCAT", 5],
    ["BRETT", 6],
    ["MEW", 6],
    ["TURBO", 6],
    ["NEIRO", 6],
    ["REZ", 5],
    ["ZK", 5],
    ["ZRO", 4],
    ["LISTA", 4],
    ["BANANA", 2],
    ["AI", 4],
    ["PEOPLE", 5],
    ["WIF", 4],
    ["SHIB", 8],
    ["1000PEPE", 5],
    ["1000SHIB", 5],
    ["1000BONK", 5],
    ["1000FLOKI", 5],
    ["1000SATS", 5],
    ["PAXG", 2],
    ["OGN", 4],
    ["DEGO", 4],
    ["HYPE", 4],
    ["RECALL", 5],
    ["JASMY", 6],
    ["NEIROETH", 6],
    ["OM", 4],
    ["PYTH", 4],
    ["ARKM", 4],
    ["ORDI", 3],
    ["MANTA", 4],
    ["SAGA", 4],
    ["WOO", 5],
    ["IO", 4],
    ["RONIN", 4],
    ["PIXEL", 5],
    ["PORTAL", 5],
    ["SUPER", 4],
    ["FLOW", 4],
    ["APE", 4],
    ["GMT", 5],
    ["ENS", 3],
    ["GMX", 2],
    ["MAGIC", 4],
    ["CELO", 4],
    ["MINA", 4],
    ["THETA", 4],
    ["SXP", 4],
    ["ARK", 4],
    ["LRC", 5],
    ["BAT", 5],
    ["QTUM", 3],
    ["ONE", 6],
    ["ONT", 4],
    ["ROSE", 5],
    ["IOTA", 4],
    ["ANKR", 6],
    ["SKL", 6],
    ["CELR", 6],
    ["HOT", 7],
    ["CFX", 5],
    ["AR", 2],
    ["ID", 5],
    ["JTO", 4],
    ["W", 4],
    ["GOAT", 5],
    ["PNUT", 5],
    ["ACT", 5],
    ["SCR", 4],
    ["MOG", 7],
    ["1000000MOG", 5],
    ["MOODENG", 5],
    ["AERO", 4],
    ["TRB", 2],
    ["KERNEL", 4],
    ["LQTY", 4],
    ["TWT", 4],
    ["RVN", 5],
    ["XMR", 2],
    ["VET", 5],
    ["HBAR", 5],
    ["QTUM", 3]
  ];

  const symbols = Array.from(
    new Map(
      FALLBACK_BASE_ASSETS.map(([baseAsset, pricePrecision]) => [
        `${baseAsset}${QUOTE_ASSET}`,
        {
          symbol: `${baseAsset}${QUOTE_ASSET}`,
          baseAsset,
          quoteAsset: QUOTE_ASSET,
          contractType: "PERPETUAL",
          status: "TRADING",
          pricePrecision,
          quantityPrecision: DEFAULT_QUANTITY_PRECISION,
        },
      ])
    ).values()
  );

  return {
    source: "built-in perp universe fallback",
    degraded: true,
    generatedAt: "2026-03-13",
    symbols,
  };
});
