CREATE TABLE IF NOT EXISTS signal_events (
  id BIGSERIAL PRIMARY KEY,
  event_id TEXT NOT NULL UNIQUE,
  source TEXT NOT NULL,
  strategy TEXT NOT NULL,
  strategy_version INTEGER,
  signal_type TEXT,
  symbol TEXT NOT NULL,
  token TEXT,
  side TEXT,
  interval TEXT,
  touch TEXT,
  strength TEXT,
  quality_score DOUBLE PRECISION,
  bias_score DOUBLE PRECISION,
  detected_at TIMESTAMPTZ,
  alerted_at TIMESTAMPTZ,
  opened_at TIMESTAMPTZ,
  event_time TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  entry_low DOUBLE PRECISION,
  entry_high DOUBLE PRECISION,
  entry_price DOUBLE PRECISION,
  tp1 DOUBLE PRECISION,
  tp2 DOUBLE PRECISION,
  stop_loss DOUBLE PRECISION,
  leverage INTEGER,
  price_precision INTEGER,
  metadata JSONB NOT NULL DEFAULT '{}'::JSONB
);

CREATE TABLE IF NOT EXISTS trade_events (
  id BIGSERIAL PRIMARY KEY,
  event_id TEXT NOT NULL UNIQUE,
  trade_id TEXT NOT NULL,
  source TEXT NOT NULL,
  strategy TEXT NOT NULL,
  strategy_version INTEGER,
  event_type TEXT NOT NULL,
  symbol TEXT NOT NULL,
  side TEXT,
  event_time TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  detected_at TIMESTAMPTZ,
  opened_at TIMESTAMPTZ,
  closed_at TIMESTAMPTZ,
  entry_price DOUBLE PRECISION,
  exit_price DOUBLE PRECISION,
  tp1 DOUBLE PRECISION,
  tp2 DOUBLE PRECISION,
  stop_loss DOUBLE PRECISION,
  leverage INTEGER,
  quantity DOUBLE PRECISION,
  margin_used DOUBLE PRECISION,
  quality_score DOUBLE PRECISION,
  return_pct DOUBLE PRECISION,
  pnl_usd DOUBLE PRECISION,
  balance_after DOUBLE PRECISION,
  metadata JSONB NOT NULL DEFAULT '{}'::JSONB
);

CREATE TABLE IF NOT EXISTS alert_deliveries (
  id BIGSERIAL PRIMARY KEY,
  delivery_id TEXT NOT NULL UNIQUE,
  source TEXT NOT NULL,
  strategy TEXT,
  event_type TEXT,
  symbol TEXT,
  title TEXT,
  destination TEXT NOT NULL,
  status TEXT NOT NULL,
  error TEXT,
  sent_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  payload JSONB NOT NULL DEFAULT '{}'::JSONB
);
